[package]
name = "dofus-dmg-calculator"
version = "1.0.0"
edition = "2024"
description = "Compute the estimated damages your Dofus spell may inflict"
authors = ["Patacode <pata.codegineer@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Patacode/dofus-dmg-calculator"
keywords = ["dofus", "damage", "calculator", "utility", "spell"]
categories = ["games", "command-line-utilities"]

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
