name: Release new version

on:
  workflow_dispatch:
    inputs:
      bumpLevel:
        description: "Bump level"
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      profile:
        description: "Cargo profile"
        default: "release"
        type: choice
        options:
          - dev
          - release
          - test
          - bench
      enabledIntegrationTests:
        description: "Execute integration tests"
        type: boolean
        default: true
      enabledBenchmarking:
        description: "Execute benchmarks"
        type: boolean
      enabledDeploymentDryRun:
        description: "Deploy in dry run mode"
        type: boolean
        default: true

jobs:
  announce:
    name: Report deployment metadata
    runs-on: ubuntu-latest
    steps:
      - name: Print metadata
        run: |
          echo "Bump level: $BUMP_LEVEL"
          echo "Profile: $PROFILE"
          echo "Integration tests: $INTEGRATION_TESTS"
          echo "Benchmarking: $BENCHMARKING"
          echo "Dry run: $DRY_RUN"
        env:
          BUMP_LEVEL: ${{ inputs.bumpLevel }}
          PROFILE: ${{ inputs.profile }}
          INTEGRATION_TESTS: ${{ inputs.enabledIntegrationTests }}
          BENCHMARKING: ${{ inputs.enabledBenchmarking }}
          DRY_RUN: ${{ inputs.enabledDeploymentDryRun }}

  build:
    name: Build crate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Generate artifacts
        run: cargo build --${{ inputs.profile }} --verbose
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crate-artifacts
          path: ./target
          retention-days: 1

  formatting-test:
    name: Test crate format
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Check code formatting
        run: cargo fmt --check

  unit-test:
    name: Test crate library code
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run unit tests
        run: cargo test --release --lib

  integration-test:
    name: Test crate binary execution
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ inputs.enabledIntegrationTests }}
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run integration tests
        run: cargo test --release --test integration_tests

  benchmark:
    name: Benchmark crate
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ inputs.enabledBenchmarking }}
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run benchmarks
        run: cargo bench --profile release

  deploy:
    name: Deploy crate
    runs-on: ubuntu-latest
    needs: [formatting-test, unit-test, integration-test, benchmark]
    if: ${{ !failure() }}
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v4
      - name: Fetch production artifacts
        uses: actions/download-artifact@v4
        with:
          name: crate-artifacts
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-release from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-release
          version: "0.25.17"
      - name: Trigger new deployment
        run: cargo release ${{ inputs.bumpLevel }} ${{ inputs.dryRun == 1 && '' || '--execute' }}

  cleanup:
    name: Cleanup artifacts
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: ${{ always() }}
    steps:
      - name: Delete all archived artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          failOnError: false
          name: crate-artifacts
